version: '3.4'

services:
  app:
    image: threax/keepass
    build:
      context: .
      dockerfile: Notes/Dockerfile
    networks:
      - appnet
    volumes:
      - type: bind
        source: ../TrustedRoots
        target: /usr/local/share/ca-certificates
      - type: bind
        source: ../DevData/notes
        target: /appdata
    labels:
      - "threax.nginx.host=notes.dev.threax.com"

networks:
  appnet:
    external: true